---
- name: Create file1
  copy:
    dest: /home/secret/folder1/file1.txt
    content:
      Text Line, in file1
      Text Line, in file1
      Text Line, {{ mytext }}

- name: Create file2
  copy:
    dest: /home/secret/folder2/file2.txt
    content:
      Text Line, in file2
      Text Line, in file2
      Text Line, {{ mytext }}
