---
- name: Create folder1
  file:
    path: /home/secret/folder1
    state: directory
    mode: 0755

- name: Create folder2
  file:
    path: /home/secret/folder2
    state: directory
    mode: 0755

- name: Create folder logs
  file:
    path: /home/secret/logs
    state: directory
    mode: 0755
