---
- name: Install Apache and Upload Web Page
  hosts: PRODUCTION_WEB
  become: yes

  vars:
    source_file: ./web_site/index.html
    destin_file: /var/www/html

  tasks:
  - name: Check and Print Linux Version
    debug: var=ansible_os_family

  - block: #=======Block for RedHat=======

      - name: Install Apache Web Server for RedHat
        yum: name=httpd state=latest

      - name: Copy MyPage to Servers
        copy: src={{ source_file }} dest={{ destin_file }} mode=0555
        notify: Restart Apache RedHat

      - name: Start Web Servers and Enable for RedHat
        service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"

  - block: #=======Block for Debian=======

      - name: Update apt packages
        apt:
          update_cache: yes

      - name: Install Apache Web Server for Debian
        apt: name=apache2 state=latest

      - name: Copy MyPage to Servers
        copy: src={{ source_file }} dest={{ destin_file }} mode=0555
        notify: Restart Apache Debian

      - name: Start Web Servers and Enable for Debian
        service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted

  - name: Restart Apache Debian
    service: name=apache2 state=restarted
