---
- name: Install Apache and Upload Web Page
  hosts: PRODUCTION_WEB
  become: yes

  vars:
    source_file: ./web_site/index.html
    destin_file: /var/www/html

  tasks:
  - name: Install Apache Web Server
    apt: name=apache2 state=latest

  - name: Copy MyPage to Servers
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache

  - name: Start Web Servers and Enable
    service: name=apache2 state=started enabled=yes

  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted
